/* Matchday Hallenturnier v3 — no backend; never automatically fetch external URLs. */
(()=>{'use strict';
const KEY='matchday_hall_v3';
const schedule=[
['2026-11-14','Union Babenberg · AHS Solar City','6+1'],
['2026-11-21','JAZ Linz Süd · Sporthalle Solar City','6+1'],
['2026-11-29','Fußballschule OÖ · Sporthalle Vöcklabruck','4+1'],
['2026-12-06','Stahl Linz · BRG Solar City','6+1'],
['2026-12-12','Fußballschule OÖ · Sporthalle Wolfsegg','4+1'],
['2026-12-20','Viktoria Marchtrenk · Großturnhalle Marchtrenk','6+1'],
['2027-01-02','Union Leonding · Rundhalle Leonding','6+1'],
['2027-01-10','Sternstein Juniors · Sporthalle Bad Leonfeld','4+1'],
['2027-01-17','Fußballschule OÖ · Sporthalle Rohrbach','4+1'],
['2027-01-24','SC Marchtrenk · Dreifachturnhalle Marchtrenk','6+1'],
['2027-02-21','Union Bad Kreuzen · Sportmittelschule Bad Kreuzen','4+1'],
['2027-02-27','ASK St. Valentin · IMS Langenhart','5+1'],
['2027-03-06','Fußballschule OÖ · Sporthalle Schärding','4+1']
].map(([date,title,format])=>({id:date,date,title,format}));
const $=id=>document.getElementById(id);
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const clean=s=>String(s??'').trim().replace(/\s+/g,' ').slice(0,90);
const unique=ls=>[...new Set(ls.map(clean).filter(Boolean))];
const parseLines=s=>unique(String(s).split(/\r?\n/));
const formatClock=sec=>`${String(Math.floor(Math.max(0,sec)/60)).padStart(2,'0')}:${String(Math.max(0,sec)%60).padStart(2,'0')}`;
function freshEvent(){return {groups:{A:[],B:[]},fixtures:[],ko:[],url:'',liveId:null,seconds:600,running:false,startedAt:null};}
function defaults(){return {active:'',team:'Unsere Kids',roster:['Spieler 1','Spieler 2','Spieler 3','Spieler 4','Spieler 5','Spieler 6'],duration:10,events:{},tournaments:[]};}
let app=defaults();try{const stored=JSON.parse(localStorage.getItem(KEY)||'null');if(stored&&stored.events&&typeof stored.events==='object'){app={...app,...stored};if(!Array.isArray(stored.tournaments))app.tournaments=null;}}catch{}
// V3 migration: only tournaments with actual saved data are migrated.
function migrateLegacy(){if(!Array.isArray(app.tournaments)){app.tournaments=Object.keys(app.events||{}).map(id=>{const entry=schedule.find(x=>x.id===id);return entry?{...entry,venue:''}:{id,date:/^\d{4}-\d\d-\d\d$/.test(id)?id:'',title:'Übernommenes Turnier',format:'Andere',venue:''};});}
app.tournaments=app.tournaments.filter(x=>x&&x.id&&app.events[x.id]);
if(!app.tournaments.some(x=>x.id===app.active))app.active=app.tournaments[0]?.id||'';
}
migrateLegacy();
for(const k of Object.keys(app.events)){const e=app.events[k];if(e&&typeof e==='object'){e.running=false;e.startedAt=null;}}
let event=()=>app.events[app.active]??(app.events[app.active]=freshEvent());
let view='plan',mainView='data',editingEventId=null,pendingImport=null,pendingImage=null,lastTick=Date.now();
function save(){try{localStorage.setItem(KEY,JSON.stringify(app));}catch{}};
function label(ev){const d=String(ev.date||'').split('-');return d.length===3?`${d[2]}.${d[1]}.${d[0]}`:'Ohne Datum';}
function setMessage(msg){$('importPreview').textContent=msg;}
function showMain(target){mainView=target==='live'&&app.active?'live':'data';$('managePane').classList.toggle('hidden',mainView!=='data');$('panel-live').classList.toggle('hidden',mainView!=='live');document.querySelectorAll('[data-main]').forEach(b=>b.classList.toggle('active',b.dataset.main===mainView));if(mainView==='live')renderLive();window.scrollTo({top:0,behavior:'smooth'});}
function showTab(tab){if(tab==='live'){showMain('live');return;}view=tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));['plan','groups','ko','import','stats'].forEach(t=>$('panel-'+t).classList.toggle('hidden',t!==tab));showMain('data');render();}
function match(home,away,group,stage='group',time='',field=''){return {id:uid(),home,away,group,stage,time,field,homeGoals:null,awayGoals:null,events:[],winner:'',completed:false};}
function scoreReady(f){return Number.isInteger(f.homeGoals)&&Number.isInteger(f.awayGoals);}
function getMatch(id){return [...event().fixtures,...event().ko].find(f=>f.id===id);}
function teamKey(v){return clean(v).toLocaleLowerCase('de');}function ourMatch(f){return f&&(teamKey(f.home)===teamKey(app.team)||teamKey(f.away)===teamKey(app.team));}
function scoreOwn(f){const ours=teamKey(f.home)===teamKey(app.team);return ours?f.homeGoals:f.awayGoals;}
function scoreOpp(f){const ours=teamKey(f.home)===teamKey(app.team);return ours?f.awayGoals:f.homeGoals;}
function validURL(v){try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u:null;}catch{return null;}}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function renderEvents(){const list=[...app.tournaments].sort((a,b)=>String(a.date).localeCompare(String(b.date)));$('eventCount').textContent=list.length+' Turniere';$('events').innerHTML=list.length?list.map(e=>`<div class="event-wrap ${e.id===app.active?'active':''}"><button type="button" class="event" data-event="${escapeHTML(e.id)}"><time>${escapeHTML(label(e))} · ${escapeHTML(e.format||'Andere')}</time><strong>${escapeHTML(e.title)}</strong>${e.venue?`<small class="location">${escapeHTML(e.venue)}</small>`:''}<small>${(app.events[e.id]?.fixtures?.length||0)+(app.events[e.id]?.ko?.length||0)} Begegnungen erfasst</small></button><div class="event-actions"><button class="btn" data-event-edit="${escapeHTML(e.id)}" type="button">✎ Bearbeiten</button><button class="btn danger" data-event-delete="${escapeHTML(e.id)}" type="button">✕ Löschen</button></div></div>`).join(''):'';}
function openEventEditor(id=null){editingEventId=id;const selected=app.tournaments.find(t=>t.id===id);$('eventEditorTitle').textContent=selected?'Turnier bearbeiten':'Neues Turnier';$('eventName').value=selected?.title||'';$('eventDate').value=selected?.date||'';$('eventVenue').value=selected?.venue||'';$('eventFormat').value=selected?.format||'6+1';$('eventEditor').classList.remove('hidden');$('eventName').focus();}
function closeEventEditor(){editingEventId=null;$('eventEditor').classList.add('hidden');}
function activateEvent(id){if(!app.tournaments.some(t=>t.id===id))return;tick();app.active=id;const ev=event();ev.running=false;$('groupA').value=(ev.groups.A||[]).join('\n');$('groupB').value=(ev.groups.B||[]).join('\n');pendingImport=null;$('applyPreview').disabled=true;render();}
function saveEvent(){const title=clean($('eventName').value);const date=$('eventDate').value;const venue=clean($('eventVenue').value);const format=$('eventFormat').value;if(!title||!/^\d{4}-\d{2}-\d{2}$/.test(date)){alert('Bitte Turniername und Datum angeben.');return;}const existing=app.tournaments.find(t=>t.id===editingEventId);if(existing){Object.assign(existing,{title,date,venue,format});}else{const id=uid();app.tournaments.push({id,title,date,venue,format});app.events[id]=freshEvent();app.events[id].seconds=app.duration*60;app.active=id;}closeEventEditor();$('groupA').value=(event().groups.A||[]).join('\n');$('groupB').value=(event().groups.B||[]).join('\n');save();render();}
function deleteEvent(id){const e=app.tournaments.find(x=>x.id===id);if(!e||!confirm('Turnier „'+e.title+'“ einschließlich seiner Ergebnisse und Torschützen unwiderruflich löschen? Bitte vorher JSON-Sicherung anlegen.'))return;delete app.events[id];app.tournaments=app.tournaments.filter(x=>x.id!==id);if(app.active===id)app.active=app.tournaments[0]?.id||'';closeEventEditor();if(app.active){$('groupA').value=(event().groups.A||[]).join('\n');$('groupB').value=(event().groups.B||[]).join('\n');}if(!app.active)showMain('data');save();render();}
function importPresetEvents(){const missing=schedule.filter(e=>!app.tournaments.some(t=>t.date===e.date&&t.title===e.title));if(!missing.length){alert('Alle 13 Saisontermine sind bereits vorhanden.');return;}if(!confirm(missing.length+' Saisontermine ergänzen? Bestehende Turniere und Ergebnisse bleiben erhalten.'))return;for(const x of missing){const id=uid();app.tournaments.push({...x,id,venue:''});app.events[id]=freshEvent();}if(!app.active)app.active=app.tournaments[0].id;$('groupA').value=(event().groups.A||[]).join('\n');$('groupB').value=(event().groups.B||[]).join('\n');save();render();}
function renderGuide(){$('statusTournament').textContent='✓ '+(app.tournaments.find(x=>x.id===app.active)?.title||'');$('statusRoster').textContent=app.team==='Unsere Kids'?'Teamname prüfen':'✓ '+app.team;$('statusFixtures').textContent=event().fixtures.length+' Begegnungen';const ready=[...event().fixtures,...event().ko].some(ourMatch);$('statusLive').textContent=ready?'✓ Bereit':'Spiel fehlt';document.querySelectorAll('.guide-step').forEach((el,i)=>el.classList.toggle('complete',i===0||i===1&&app.team!=='Unsere Kids'||i===2&&event().fixtures.length>0||i===3&&ready));}

function rankings(group){const teams=event().groups[group]||[];const rows=teams.map(name=>({name,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0}));const map=new Map(rows.map(r=>[r.name,r]));event().fixtures.filter(f=>f.group===group&&f.stage==='group'&&scoreReady(f)).forEach(f=>{const h=map.get(f.home),a=map.get(f.away);if(!h||!a)return;h.p++;a.p++;h.gf+=f.homeGoals;h.ga+=f.awayGoals;a.gf+=f.awayGoals;a.ga+=f.homeGoals;if(f.homeGoals>f.awayGoals){h.w++;a.l++;h.pts+=3;}else if(f.homeGoals<f.awayGoals){a.w++;h.l++;a.pts+=3;}else {h.d++;a.d++;h.pts++;a.pts++;}});rows.forEach(x=>x.gd=x.gf-x.ga);return rows.sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.name.localeCompare(b.name,'de'));}
function renderTables(){let html='';for(const g of ['A','B']){let rows=rankings(g);if(!rows.length)continue;html+=`<h3>Gruppe ${g}</h3><div class="scroll"><table class="table"><thead><tr><th>#</th><th>Team</th><th>Sp.</th><th>S</th><th>U</th><th>N</th><th>Tore</th><th>Diff.</th><th>Pkt.</th></tr></thead><tbody>${rows.map((r,i)=>`<tr class="${r.name===app.team?'ours':''}"><td>${i+1}</td><td>${escapeHTML(r.name)}</td><td>${r.p}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf}:${r.ga}</td><td class="num">${r.gd>0?'+':''}${r.gd}</td><td class="num"><strong>${r.pts}</strong></td></tr>`).join('')}</tbody></table></div>`;} $('tables').innerHTML=html||'<div class="muted">Noch keine Gruppen angelegt.</div>';}
function matchMarkup(f){const isOurs=ourMatch(f);const result=scoreReady(f)?`${f.homeGoals}:${f.awayGoals}`:'– : –';return `<div class="matchline"><div class="match"><div class="name">${escapeHTML(f.home||'Offen')}<small>${escapeHTML(f.group==='A'||f.group==='B'?'Gruppe '+f.group:f.stage==='semi'?'Halbfinale':f.stage==='final'?'Finale':'Freies Spiel')}${f.time?' · '+escapeHTML(f.time):''}</small></div><div class="score">${result}</div><div class="name">${escapeHTML(f.away||'Offen')}<small>${escapeHTML(f.field)}</small></div></div><button class="btn" data-edit="${f.id}">${isOurs?'Live':'Ergebnis'}</button></div>`;}
function renderFixtures(){const fixtures=[...event().fixtures,...event().ko];$('fixtures').innerHTML=fixtures.length?fixtures.map(matchMarkup).join(''):'<p>Hier erscheinen Begegnungen nach dem Import oder nach Erstellen der Gruppenrunde.</p>';}
function winner(f){if(!f||!scoreReady(f)||!f.home||!f.away)return '';if(f.homeGoals>f.awayGoals)return f.home;if(f.homeGoals<f.awayGoals)return f.away;return f.winner===f.home||f.winner===f.away?f.winner:'';}
function syncFinal(){const ko=event().ko; if(ko.length!==3)return;const x=winner(ko[0]),y=winner(ko[1]);const final=ko[2];if(final.home!==x||final.away!==y){final.home=x;final.away=y;final.homeGoals=null;final.awayGoals=null;final.events=[];final.winner='';if(event().liveId===final.id){event().running=false;event().liveId=null;}}}
function renderKO(){syncFinal();const ko=event().ko;if(ko.length!==3){$('bracket').innerHTML='<p>Halbfinale noch nicht angelegt. Gruppenstände oder manuelle Team-Auswahl verwenden.</p>';return;}
$('bracket').innerHTML=`<div><h3>Halbfinale</h3>${ko.slice(0,2).map((f,i)=>`<div class="slot"><small>HF ${i+1}</small><strong>${escapeHTML(f.home||'Offen')} ${scoreReady(f)?f.homeGoals:'–'} : ${scoreReady(f)?f.awayGoals:'–'} ${escapeHTML(f.away||'Offen')}</strong><small>${winner(f)?'Sieger: '+escapeHTML(winner(f)):'Sieger offen'}</small><button class="btn" style="margin-top:7px" data-edit="${f.id}">Ergebnis</button></div>`).join('')}</div><div><h3>Finale</h3><div class="slot"><small>Finale</small><strong>${escapeHTML(ko[2].home||'HF 1 Sieger')} ${scoreReady(ko[2])?ko[2].homeGoals:'–'} : ${scoreReady(ko[2])?ko[2].awayGoals:'–'} ${escapeHTML(ko[2].away||'HF 2 Sieger')}</strong><small>${winner(ko[2])?'🏆 '+escapeHTML(winner(ko[2])):'Noch offen'}</small><button class="btn" style="margin-top:7px" data-edit="${ko[2].id}" ${ko[2].home&&ko[2].away?'':'disabled'}>Ergebnis</button></div></div>`;}
function liveSelect(){syncFinal();const options=[...event().fixtures,...event().ko].filter(ourMatch).filter(f=>f.home&&f.away);let id=event().liveId;if(!options.some(f=>f.id===id)){id=options.find(f=>!f.completed&&!scoreReady(f))?.id||options.find(f=>!f.completed)?.id||options.at(-1)?.id||null;event().liveId=id;event().running=false;event().seconds=app.duration*60;}
$('liveChoice').innerHTML=options.length?options.map(f=>`<option value="${f.id}">${escapeHTML(f.group?'Gruppe '+f.group:f.stage==='semi'?'Halbfinale':f.stage==='final'?'Finale':'Freies Spiel')} · ${escapeHTML(f.home)} – ${escapeHTML(f.away)} ${scoreReady(f)?'('+f.homeGoals+':'+f.awayGoals+')':''}</option>`).join(''):'<option value="">Noch kein Spiel mit eurem Team</option>';$('liveChoice').value=id||'';return getMatch(id);}
function renderLive(){const f=liveSelect();if(!f){$('quickStart').classList.remove('hidden');$('liveContent').innerHTML='';return;}$('quickStart').classList.add('hidden');
let a=f.homeGoals??0,b=f.awayGoals??0;let oursHome=teamKey(f.home)===teamKey(app.team);const ourScore=oursHome?a:b,otherScore=oursHome?b:a;const opponent=oursHome?f.away:f.home;
$('liveContent').innerHTML=`<div class="muted" style="text-align:center;margin-top:14px">${escapeHTML(f.group?'Gruppe '+f.group:f.stage==='semi'?'Halbfinale':f.stage==='final'?'Finale':'Freies Spiel')} ${escapeHTML(f.time?'· '+f.time:'')} ${escapeHTML(f.field?'· '+f.field:'')}</div><div class="hero"><div class="side"><small>UNSER TEAM</small><h3>${escapeHTML(app.team)}</h3><div class="digits">${ourScore}</div></div><div class="colon">:</div><div class="side"><small>GEGNER</small><h3>${escapeHTML(opponent)}</h3><div class="digits">${otherScore}</div></div></div><div class="goalbuttons"><button id="goalOurs">⚽ Tor für uns +</button><button id="goalOther">⚽ Gegentor +</button></div><div class="row"><button class="btn" id="undoGoal" ${!f.events.length?'disabled':''}>↶ Letztes Tor zurück</button><button class="btn" id="correctScore">✎ Ergebnis korrigieren</button></div><div class="clock" id="hallClock">${formatClock(event().seconds)}</div><div class="row" style="justify-content:center"><button class="btn primary" id="hallStart">${event().running?'⏸ Pause':'▶ Start'}</button><button class="btn" id="hallTimerReset">↺ Timer</button><button class="btn" id="hallTimerPlus">+ 1 min</button></div><h3>⚽ Tore</h3><div class="stack">${f.events.length?f.events.map(g=>`<div class="muted">${g.side==='ours'?'🟢':'🔵'} ${escapeHTML(g.player)} · ${escapeHTML(g.time)}</div>`).join(''):'<p>Dieses Spiel hat noch keine erfassten Treffer.</p>'}</div><div class="row" style="margin-top:16px"><button class="btn primary" id="hallComplete">✓ Spiel abschließen</button></div><p class="hint">Nach der Spielzeit automatisch angezeigte Uhrzeit ist kein offizieller Schlusspfiff. Du kannst jedes Resultat später ändern.</p>`;
$('goalOurs').onclick=()=>{const players=unique(app.roster);const text=prompt('Torschütze (Name eingeben):\n'+players.map((n,i)=>`${i+1}: ${n}`).join('\n'),'1');if(text===null)return;const idx=Number(text);const name=Number.isInteger(idx)&&idx>=1&&idx<=players.length?players[idx-1]:clean(text)||'Unbekannt';addGoal(f,'ours',name);};
$('goalOther').onclick=()=>addGoal(f,'theirs','Gegner');$('undoGoal').onclick=()=>{const g=f.events.pop();if(!g)return;const home=(g.side==='ours')===oursHome;let key=home?'homeGoals':'awayGoals';f[key]=Math.max(0,(f[key]??0)-1);afterScore();};
$('correctScore').onclick=()=>editScore(f.id);$('hallStart').onclick=()=>{tick();event().running=!event().running;lastTick=Date.now();save();renderLive();};$('hallTimerReset').onclick=()=>{event().running=false;event().seconds=app.duration*60;save();renderLive();};$('hallTimerPlus').onclick=()=>{event().seconds+=60;save();renderLive();};$('hallComplete').onclick=()=>{tick();event().running=false;save();if(confirm(`Spiel ${app.team} gegen ${opponent} mit ${ourScore}:${otherScore} abschließen?`)){f.homeGoals??=0;f.awayGoals??=0;f.completed=true;event().liveId=null;save();showTab('plan');}else renderLive();};}
function addGoal(f,side,player){tick();let home=(side==='ours')===(teamKey(f.home)===teamKey(app.team));const key=home?'homeGoals':'awayGoals';f.homeGoals=(f.homeGoals??0)+(home?1:0);f.awayGoals=(f.awayGoals??0)+(home?0:1);f.events.push({side,player,time:formatClock(app.duration*60-event().seconds)});afterScore();}
function afterScore(){syncFinal();save();render();}
function tick(){const e=event();if(!e.running)return;const now=Date.now(),seconds=Math.floor((now-lastTick)/1000);if(seconds<=0)return;lastTick+=seconds*1000;e.seconds=Math.max(0,e.seconds-seconds);if(!e.seconds){e.running=false;if(navigator.vibrate)navigator.vibrate([150,100,150]);}const clock=$('hallClock');if(clock)clock.textContent=formatClock(e.seconds);save();}
setInterval(tick,300);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});
function editScore(id){const f=getMatch(id);if(!f)return;if(ourMatch(f)&&f.id!==event().liveId){event().running=false;event().liveId=f.id;event().seconds=app.duration*60;}const h=prompt(`${f.home||'Offen'}: Tore (leer = nicht gespielt)`,f.homeGoals??'');if(h===null)return;const a=prompt(`${f.away||'Offen'}: Tore (leer = nicht gespielt)`,f.awayGoals??'');if(a===null)return;if((h.trim()!==''&&!/^\d{1,2}$/.test(h.trim()))||(a.trim()!==''&&!/^\d{1,2}$/.test(a.trim()))){alert('Bitte 0 bis 99 oder beide Felder leer eingeben.');return;}if((h.trim()==='')!==(a.trim()==='')){alert('Beide Werte eingeben oder beide leer lassen.');return;}f.homeGoals=h.trim()===''?null:Number(h);f.awayGoals=a.trim()===''?null:Number(a);f.events=[];f.winner='';if(scoreReady(f)&&f.homeGoals===f.awayGoals&&f.stage!=='group'){const who=prompt('Unentschieden nach regulärer Zeit: Sieger bei Entscheidungsschießen?\n1: '+f.home+'\n2: '+f.away+'\nLeer = noch offen','');if(who==='1')f.winner=f.home;else if(who==='2')f.winner=f.away;}afterScore();}
function renderStats(){const fs=[...event().fixtures,...event().ko].filter(ourMatch).filter(scoreReady),wins=fs.filter(f=>scoreOwn(f)>scoreOpp(f)).length,draws=fs.filter(f=>scoreOwn(f)===scoreOpp(f)).length,losses=fs.filter(f=>scoreOwn(f)<scoreOpp(f)).length,goals=fs.reduce((n,f)=>n+scoreOwn(f),0),conceded=fs.reduce((n,f)=>n+scoreOpp(f),0);
$('stats').innerHTML=[['Spiele',fs.length],['Siege',wins],['Remis',draws],['Niederlagen',losses],['Tore',goals],['Gegentore',conceded]].map(([l,v])=>`<div class="statbox"><b>${v}</b><small>${l}</small></div>`).join('');const names={};for(const f of [...event().fixtures,...event().ko].filter(ourMatch))for(const g of f.events||[])if(g.side==='ours')names[g.player]=(names[g.player]||0)+1;const sorted=Object.entries(names).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'de'));$('scorers').innerHTML=sorted.length?sorted.map(([n,c],i)=>`<div class="match"><span>${i+1}. ${escapeHTML(n)}</span><span class="pill">${c} ⚽</span><span></span></div>`).join(''):'<p class="muted">Noch keine Torschützen erfasst.</p>';}
function render(){renderEvents();const ready=Boolean(app.active);$('workspace').classList.toggle('hidden',!ready);$('emptyView').classList.toggle('hidden',ready);if(!ready){$('liveContent').innerHTML='';save();return;}renderGuide();renderTables();renderFixtures();renderKO();renderStats();renderLive();$('onlineUrl').value=event().url||'';save();}
function teamsForKO(){const a=rankings('A').map(x=>x.name),b=rankings('B').map(x=>x.name);if(a.length>=2&&b.length>=2)return [a[0],b[1],b[0],a[1]];if(a.length>=4&&!b.length)return [a[0],a[3],a[1],a[2]];return null;}
function groupMake(){const e=event();const groups={A:parseLines($('groupA').value),B:parseLines($('groupB').value)};if(!groups.A.length&&!groups.B.length){alert('Bitte mindestens eine Mannschaft erfassen.');return false;}if(new Set([...groups.A,...groups.B]).size!==groups.A.length+groups.B.length){alert('Ein Team darf nicht in beiden Gruppen vorkommen.');return false;}e.groups=groups;save();render();return true;}
function generate(){if(!groupMake())return;const e=event();const old=e.fixtures.filter(f=>f.stage==='group');if(old.length&&!confirm('Vorhandene Gruppenspiele und Ergebnisse ersetzen?'))return;
const other=e.fixtures.filter(f=>f.stage!=='group');const fs=[];for(const group of ['A','B']){const ts=e.groups[group];for(let round=0;round<ts.length-1;round++)for(let col=round+1;col<ts.length;col++)fs.push(match(ts[round],ts[col],group));}e.fixtures=[...other,...fs];e.running=false;e.liveId=null;render();showTab('plan');}
function createKO(){const ts=teamsForKO();let teams=ts;if(ts&&[...event().fixtures].some(f=>f.stage==='group'&&!scoreReady(f))&&!confirm('Nicht alle Gruppenspiele haben Ergebnisse. Die Halbfinalpaarungen basieren auf dem momentanen Tabellenstand. Trotzdem fortfahren?'))return;if(!teams){const all=unique([...event().groups.A,...event().groups.B,...event().fixtures.flatMap(f=>[f.home,f.away])]);if(all.length<4){alert('Bitte mindestens 4 Mannschaften anlegen.');return;}const input=prompt('Vier Halbfinalteams, mit Semikolon getrennt:\nHF1: Team 1 – Team 2; HF2: Team 3 – Team 4',all.slice(0,4).join('; '));if(input===null)return;teams=input.split(';').map(clean);if(teams.length!==4||teams.some(x=>!x)||new Set(teams).size!==4){alert('Genau vier verschiedene Teams angeben.');return;}}
if(event().ko.length&&!confirm('Vorhandene K.-o.-Ergebnisse ersetzen?'))return;event().ko=[match(teams[0],teams[1],'','semi'),match(teams[2],teams[3],'','semi'),match('','','','final')];event().running=false;event().liveId=null;render();}
function addFixture(){const group=prompt('Gruppe (A/B), oder F für freie Begegnung:','A');if(group===null)return;const g=group.trim().toUpperCase();if(!['A','B','F'].includes(g)){alert('A, B oder F verwenden.');return;}const home=clean(prompt('Heimmannschaft:','')??'');if(!home)return;const away=clean(prompt('Gastmannschaft:','')??'');if(!away||home===away){alert('Zwei unterschiedliche Teams nötig.');return;}const time=clean(prompt('Uhrzeit (optional):','')??'');const field=clean(prompt('Spielfeld (optional):','')??'');const f=match(home,away,g==='F'?'':g,'group',time,field);event().fixtures.push(f);if(g!=='F'){for(const n of [home,away])if(!event().groups[g].includes(n))event().groups[g].push(n);}render();}
function parseCSV(src){const lines=String(src).replace(/^\ufeff/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)throw Error('Datei leer');const head=lines[0];const sep=[';',',','\t'].sort((a,b)=>(head.split(b).length-head.split(a).length))[0];function parseRow(row){const res=[];let cur='',quoted=false;for(let i=0;i<row.length;i++){const c=row[i];if(c==='"'){if(quoted&&row[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(c===sep&&!quoted){res.push(cur.trim());cur='';}else cur+=c;}res.push(cur.trim());return res;}
const headers=parseRow(lines[0]).map(x=>x.toLowerCase().replace(/[ _\-]/g,''));const field=(names)=>headers.findIndex(h=>names.includes(h));let gi=field(['gruppe','group','pool']),ti=field(['mannschaft','team','verein']),hi=field(['heim','home','team1','heimmannschaft']),ai=field(['gast','away','team2','gastmannschaft']),time=field(['uhrzeit','zeit','time','anpfiff']),pitch=field(['feld','court','field','spielfeld']);const groupRows={A:[],B:[]},fs=[];
if(hi<0||ai<0){if(ti<0)throw Error('CSV benötigt „Gruppe;Mannschaft“ oder „Gruppe;Heim;Gast“ als Spalten.');}
for(let i=1;i<lines.length;i++){const cells=parseRow(lines[i]);const g=(gi<0?'A':clean(cells[gi]).replace(/^gruppe\s*/i,'').toUpperCase());if(!['A','B'].includes(g))continue;if(hi>=0&&ai>=0){const home=clean(cells[hi]),away=clean(cells[ai]);if(!home||!away||home===away)continue;fs.push(match(home,away,g,'group',time<0?'':clean(cells[time]),pitch<0?'':clean(cells[pitch])));groupRows[g].push(home,away);}else{const n=clean(cells[ti]);if(n)groupRows[g].push(n);}}
return {groups:{A:unique(groupRows.A),B:unique(groupRows.B)},fixtures:fs};}
function parseJSON(s){const obj=JSON.parse(s);if(!obj||typeof obj!=='object'||!obj.groups)throw Error('JSON benötigt „groups“ und optional „fixtures“.');const groups={A:unique(obj.groups.A||[]),B:unique(obj.groups.B||[])};const fixtures=(obj.fixtures||[]).map(f=>match(clean(f.home),clean(f.away),['A','B'].includes(f.group)?f.group:'A','group',clean(f.time),clean(f.field))).filter(f=>f.home&&f.away&&f.home!==f.away);return {groups,fixtures};}
function parsePhotoText(input){const rows=input.split(/\r?\n/).map(clean).filter(Boolean);let current='A';const groups={A:[],B:[]};for(const row of rows){const match=row.match(/^gr(?:uppe|\.)?\s*([ab])\s*:?$/i);if(match){current=match[1].toUpperCase();continue;}if(/^([\d]{1,2}[:.][\d]{2}|\d{1,2}\s*[-:]\s*\d{1,2}|spielplan|uhrzeit|platz|spielfeld|datum|zeit|rang|tabelle|punkte|tore|heim|gast|finale|halbfinale)/i.test(row))continue;
const n=clean(row.replace(/^\d{1,2}[.)]\s*/,''));if(n&&n.length>2&&n.length<80)groups[current].push(n);}groups.A=unique(groups.A);groups.B=unique(groups.B);if(!groups.A.length&&!groups.B.length)throw Error('Keine plausiblen Teamnamen erkannt. Text manuell korrigieren.');return {groups,fixtures:[]};}
function preview(parsed,source){pendingImport=parsed;const count=parsed.groups.A.length+parsed.groups.B.length;$('applyPreview').disabled=!count&&!parsed.fixtures.length;
$('importPreview').innerHTML=`<strong>${escapeHTML(source)} · Importvorschau</strong><br>Gruppe A: ${escapeHTML(parsed.groups.A.join(' · ')||'–')}<br>Gruppe B: ${escapeHTML(parsed.groups.B.join(' · ')||'–')}<br>${parsed.fixtures.length} Spielpaarungen erkannt.<br><small>Bitte vor Übernahme prüfen: Namen, Paarungen und Zeiten. Bei Fotos werden bewusst nur Kandidaten für Teamnamen vorgeschlagen, keine sicheren Paarungen.</small>`;}
function applyImport(){if(!pendingImport)return;if((event().fixtures.length||event().ko.length)&&!confirm('Gruppen und Gruppenspielplan ersetzen? Vorhandene Gruppenergebnisse werden gelöscht, die Finalrunde bleibt bestehen.'))return;event().groups={...pendingImport.groups};event().fixtures=pendingImport.fixtures;event().liveId=null;event().running=false;pendingImport=null;$('applyPreview').disabled=true;render();showTab('groups');}
async function recognize(){if(!pendingImage){$('ocrStatus').textContent='Bitte zuerst ein Bild auswählen.';return;}$('readPhoto').disabled=true;$('ocrStatus').textContent='OCR wird geladen – Internetverbindung erforderlich …';try{if(!window.Tesseract){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>reject(Error('OCR-Bibliothek nicht geladen'));document.head.append(s);});}const worker=await Tesseract.createWorker('deu+eng',1,{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent=`Lese Bild: ${Math.round(m.progress*100)} %`;}});try{const result=await worker.recognize(pendingImage);$('rawImport').value=result.data.text;$('ocrStatus').textContent='Erkannt. Bitte Teamnamen im Textfeld sorgfältig überprüfen.';preview(parsePhotoText(result.data.text),'Foto (ungeprüfter OCR-Text)');}finally{await worker.terminate();}}catch(error){$('ocrStatus').textContent='Fotoerkennung derzeit nicht verfügbar: '+error.message+'. Das Foto bleibt sichtbar; bitte Teamnamen im Textfeld eingeben.';}finally{$('readPhoto').disabled=false;}}
function csvQuote(v){return '"'+String(v??'').replace(/"/g,'""')+'"';}
function exportCSV(){const ev=event();let result=['Phase;Gruppe;Heim;Gast;Tore Heim;Tore Gast;Uhrzeit;Feld;Sieger'];for(const f of [...ev.fixtures,...ev.ko])result.push([f.stage,f.group,f.home,f.away,f.homeGoals??'',f.awayGoals??'',f.time,f.field,winner(f)].map(csvQuote).join(';'));result.push('');result.push('Torschütze;Tore');const names={};for(const f of [...ev.fixtures,...ev.ko])for(const g of f.events||[])if(g.side==='ours')names[g.player]=(names[g.player]||0)+1;for(const [name,total] of Object.entries(names).sort((a,b)=>b[1]-a[1]))result.push([name,total].map(csvQuote).join(';'));download('hallenturnier-'+app.active+'.csv','\ufeff'+result.join('\r\n'),'text/csv;charset=utf-8');}
function init(){const prev=app.events[app.active];$('teamName').value=app.team;$('roster').value=app.roster.join('\n');$('matchLength').value=app.duration;$('groupA').value=(prev?.groups.A||[]).join('\n');$('groupB').value=(prev?.groups.B||[]).join('\n');render();
$('events').onclick=e=>{const del=e.target.closest('[data-event-delete]');if(del){deleteEvent(del.dataset.eventDelete);return;}const edit=e.target.closest('[data-event-edit]');if(edit){openEventEditor(edit.dataset.eventEdit);return;}const b=e.target.closest('[data-event]');if(b)activateEvent(b.dataset.event);};
$('tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b)showTab(b.dataset.tab);};
$('mainTabs').onclick=e=>{const b=e.target.closest('[data-main]');if(b)showMain(b.dataset.main);};
$('createEvent').onclick=()=>openEventEditor();$('cancelEvent').onclick=closeEventEditor;$('saveEvent').onclick=saveEvent;$('importPresets').onclick=importPresetEvents;
$('setupGuide').onclick=e=>{const jump=e.target.closest('[data-jump]');if(jump)showTab(jump.dataset.jump);};
$('quickStartButton').onclick=()=>{if(!app.active)return;const opp=clean($('quickOpponent').value);if(!opp||teamKey(opp)===teamKey(app.team)){alert('Bitte einen gültigen Gegnernamen eingeben.');return;}const f=match(app.team,opp,'','friendly');event().fixtures.push(f);event().liveId=f.id;event().running=false;event().seconds=app.duration*60;$('quickOpponent').value='';save();renderLive();render();};
$('saveTeam').onclick=()=>{const old=app.team,oldDuration=app.duration;app.team=clean($('teamName').value)||'Unsere Kids';app.roster=parseLines($('roster').value).slice(0,40);const minutes=Number($('matchLength').value);app.duration=Number.isFinite(minutes)?Math.min(90,Math.max(1,Math.round(minutes))):10;for(const ev of Object.values(app.events)){if(ev.seconds>0&&ev.seconds===oldDuration*60)ev.seconds=app.duration*60;} // Existing scores are deliberately not renamed.
if(old!==app.team)alert('Teamname geändert. Bereits erfasste Begegnungen werden nicht automatisch umbenannt; bitte dort den bisherigen Namen prüfen.');event().seconds=app.duration*60;save();render();};
$('saveGroups').onclick=groupMake;$('generateGroups').onclick=generate;$('buildKO').onclick=createKO;$('clearKO').onclick=()=>{if(event().ko.length&&confirm('Finalrunde und ihre Ergebnisse löschen?')){event().ko=[];event().liveId=null;render();}};
$('addFixture').onclick=addFixture;$('fixtures').onclick=e=>{const b=e.target.closest('[data-edit]');if(!b)return;const f=getMatch(b.dataset.edit);if(ourMatch(f)){event().liveId=f.id;event().running=false;event().seconds=app.duration*60;showTab('live');}else editScore(f.id);};$('bracket').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)editScore(b.dataset.edit);};
$('liveChoice').onchange=e=>{event().running=false;event().seconds=app.duration*60;event().liveId=e.target.value;renderLive();save();};
async function importFileHandler(e){const file=e.target.files[0];if(!file)return;pendingImport=null;$('applyPreview').disabled=true;pendingImage=null;$('photoPreview').classList.add('hidden');$('rawImport').value='';$('ocrStatus').textContent='';try{if(file.type.startsWith('image/')||/\.(png|jpe?g|webp)$/i.test(file.name)){pendingImage=file;$('photoPreview').src=URL.createObjectURL(file);$('photoPreview').classList.remove('hidden');setMessage('Foto geladen. „Text aus Foto erkennen“ tippen oder Mannschaften manuell eintragen.');return;}const text=await file.text();$('rawImport').value=text.slice(0,50000);const parsed=/\.json$/i.test(file.name)?parseJSON(text):parseCSV(text);preview(parsed,'Datei '+file.name);}catch(err){setMessage('Importfehler: '+err.message);}}
$('importFile').onchange=importFileHandler;$('cameraPhoto').onchange=importFileHandler;
$('readPhoto').onclick=recognize;$('previewText').onclick=()=>{try{const raw=$('rawImport').value.trim();if(!raw)throw Error('Textfeld leer');let parsed;if(raw.startsWith('{'))parsed=parseJSON(raw);else if(/^\s*(gruppe|group)\s*[;,\t]/i.test(raw)||/\b(heim|home|mannschaft|team)\b\s*[;,\t]/i.test(raw.split('\n')[0]))parsed=parseCSV(raw);else parsed=parsePhotoText(raw);preview(parsed,'Textvorschau');}catch(err){pendingImport=null;$('applyPreview').disabled=true;setMessage(err.message);}};$('applyPreview').onclick=applyImport;
$('saveUrl').onclick=()=>{const val=$('onlineUrl').value.trim();if(val&&!validURL(val)){alert('Bitte eine gültige http(s)-Adresse eingeben.');return;}event().url=val;save();alert('Link gespeichert.');};$('openUrl').onclick=()=>{const u=validURL($('onlineUrl').value.trim());if(!u)return alert('Zuerst einen gültigen Link eingeben.');window.open(u.href,'_blank','noopener,noreferrer');};$('importUrl').onclick=async()=>{const u=validURL($('onlineUrl').value.trim());if(!u)return alert('Bitte eine CSV-/JSON-URL eingeben.');if(!confirm('Öffentliche CSV-/JSON-Datei von der angegebenen URL abrufen?'))return;setMessage('Rufe Datei ab …');try{const response=await fetch(u.href,{mode:'cors',credentials:'omit'});if(!response.ok)throw Error('HTTP '+response.status);const data=await response.text();if(data.length>500000)throw Error('Datei zu groß');preview(u.pathname.toLowerCase().endsWith('.json')?parseJSON(data):parseCSV(data),'Online-Datei (manuell abgerufen)');event().url=u.href;save();}catch(err){setMessage('Automatischer Import nicht möglich ('+err.message+'). Die offizielle Website kann weiterhin separat geöffnet werden.');}};
$('backup').onclick=()=>download('matchday-hall-sicherung.json',JSON.stringify(app,null,2),'application/json');$('restore').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const obj=JSON.parse(await file.text());if(!obj.events||typeof obj.events!=='object')throw Error('Keine passende Matchday-Sicherung');if(!confirm('Die gespeicherte Hallensaison vollständig durch diese Sicherung ersetzen?'))return;app={...defaults(),...obj};if(!Array.isArray(obj.tournaments))app.tournaments=null;for(const ev of Object.values(app.events)){ev.running=false;ev.startedAt=null;}migrateLegacy();$('teamName').value=app.team;$('roster').value=app.roster.join('\n');$('matchLength').value=app.duration;$('groupA').value=event().groups.A.join('\n');$('groupB').value=event().groups.B.join('\n');render();alert('Sicherung wiederhergestellt.');}catch(err){alert('Fehler beim Laden: '+err.message);}finally{e.target.value='';}};
$('csvExport').onclick=exportCSV;$('resetEvent').onclick=()=>{if(confirm('Alle Daten nur für dieses Hallenturnier löschen? Vorher JSON sichern.')){app.events[app.active]=freshEvent();$('groupA').value='';$('groupB').value='';render();}};
if('serviceWorker' in navigator&&(location.protocol==='https:'||location.hostname==='localhost'))navigator.serviceWorker.register('./sw.js').catch(()=>{});}
init();
showMain('data');
})();